USE CATALOGO

INSERT INTO GENERO (nomeGenero)
VALUES ('AÇÃO')

SELECT * FROM GENERO

--DELETE FROM GENERO WHERE idGenero  = 4
--DELETE FROM GENERO WHERE idGenero in(2,3)

INSERT INTO FILME (idGenero,tituloFilme)
VALUES (1,'SE BEBER NAO CASE')

--DELETE FROM GENERO